### ISSUE TITLE
Problem with creating a MidiIn() object.

### ISSUE THREAD

**Issue by maowlmad** [gesellkammer/rtmidi2#1]
Hi, 
I don't manage to create an instance of MidiIn() in python 3.2.

>>> from rtmidi2 import MidiIn
>>> midi_in = MidiIn()

MidiInDummy: This class provides no functionality.

>>>

What does this message mean ?

**Comment by gesellkammer** [comment]
Are you on linux?

If you are, then it should be fixed now.

**Comment by artfwo** [comment]
@gesellkammer can you push this fix to PyPI as well? Thanks!

**Comment by gesellkammer** [comment]
I don't support PyPI anymore, if you need to install via pip use

pip install git+https://github.com/gesellkammer/rtmidi2@master#egg=rtmidi2
