### ISSUE TITLE
Build failing with latest `cython`

### ISSUE THREAD

**Issue by jonathanhogg** [gesellkammer/rtmidi2#10]
The build fails with the new `cython` version 3, which is now the latest stable release and thus being picked up automatically by the build requirements.

```
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
          cdef void _set_callback(self, callback):
              """set callback. If already set, cancels previous callback"""
              if self.py_callback is not None:
                  self._cancel_callback()
              self.py_callback = callback
              self.thisptr.setCallback(midi_in_callback, <void*>callback)
                                       ^
      ------------------------------------------------------------
      
      rtmidi2.pyx:334:33: Cannot assign type 'void (double, vector[unsigned char] *, void *) except * nogil' to 'RtMidiCallback'
```

There are actually 3 of these errors on different lines, but they're all setting the callback. There's also a bunch of warnings about how `DEF` is now deprecated.

I've not had a look at the code so I'm not sure if these are quick fixes or whether it's better to just explicitly mark that the build requires `cython<3.0.0` for the moment.

**Comment by gesellkammer** [comment]
Thanks for the heads up. This has been fixed in git and in the latest version (1.3) in pypi.
