### ISSUE TITLE
Informations request.

### ISSUE THREAD

**Issue by ZelectroLab** [gesellkammer/rtmidi2#2]
Hi, sorry for tag this as an issue (i was not able to find another way for communicating).
I've just started using rtmidi2 (and in general python...) i'm working around a personal project (live music keyboards control). Everithing work fine, really fine, and i'm not far to my goal. Just i'm not able to send program changes using the .send_messages() command. I've tried all combinations of parameter using the help reference (here below). So i need help for setting up the right sintax/conf just for pc sending. Sorry for be so..... bad... thank you a lot! Giovanni.

python 3.8
Mac osx high sierra

        """
        messagetype:
            NOTEON     144
            CC         176
            NOTEOFF    128
            PROGCHANGE 192
            PITCHWHEEL 224
        messages: a list of tuples of the form (channel, value1, value2), or a numpy 2D array with 3 columns and n rows
        where channel is an int between 0-15, value1 is the midinote or ccnumber, etc, and value2 is the value of the message (velocity, control value, etc)

        Example
        -------

        # send multiple noteoffs as noteon with velocity 0 for hosts which do not implement the noteoff message

        m = MidiOut()
        m.open_port()
        messages = [(0, i, 0) for i in range(127)]
        m.send_messages(144, messages)
        """

**Comment by gesellkammer** [comment]
Thanks for reporting this. I will take a look. For the moment you can use send_raw to send program changes

```python

import rtmidi2
device = rtmidi2.MidiOut()
device.open_virtual_port("myport")
# send program change 2 to midichannel 1
device.send_raw(192, 2)
```

**Comment by ZelectroLab** [comment]
Dear geselkammer,
Thank for fast reply! raw data work fine adn also respond to my needs. all the best! 
Giovanni.
