### ISSUE TITLE
crash/exception on send_noteon_many

### ISSUE THREAD

**Issue by Demolishun** [gesellkammer/rtmidi2#2]
I found an issue with your latest version of rtmidi2 python wrapper.  When I try to use the send_noteon_many command it will crash the program.  As in python.exe dies.

Here is the test code:
```
import rtmidi2
import time

def main():
  print "in ports:", rtmidi2.get_in_ports()
  print "out ports:", rtmidi2.get_out_ports()

  midi_out = rtmidi2.MidiOut().open_port(0)
  # open the first available port
  #midi_out.open_port(0)
  # send C3 with vel. 100 on channel 1
  midi_out.send_noteon(0, 48, 100)

  time.sleep(2)

  #midi_out = MidiOut().open_port()
  notes = range(127)
  velocities = [90] * len(notes)
  midi_out.send_noteon_many(0, notes, velocities)
  time.sleep(5)
  #midi_out.send_noteon_many(0, notes, [0] * len(notes))

if __name__ == '__main__':
    main()
```
In the above code the first node from send_noteon works fine.

The error code is this:
```
Traceback (most recent call last):
  File "<string>", line 73, in execInThread
  File "C:\Program Files (x86)\PyScripter\Lib\rpyc.zip\rpyc\core\netref.py", line 196, in __call__
  File "C:\Program Files (x86)\PyScripter\Lib\rpyc.zip\rpyc\core\netref.py", line 71, in syncreq
  File "C:\Program Files (x86)\PyScripter\Lib\rpyc.zip\rpyc\core\protocol.py", line 431, in sync_request
  File "C:\Program Files (x86)\PyScripter\Lib\rpyc.zip\rpyc\core\protocol.py", line 379, in serve
  File "C:\Program Files (x86)\PyScripter\Lib\rpyc.zip\rpyc\core\protocol.py", line 337, in _recv
  File "C:\Program Files (x86)\PyScripter\Lib\rpyc.zip\rpyc\core\channel.py", line 50, in recv
  File "C:\Program Files (x86)\PyScripter\Lib\rpyc.zip\rpyc\core\stream.py", line 166, in read
EOFError: [Errno 10054] An existing connection was forcibly closed by the remote host
```
Edit:
I just realized that error code is just the connection to my IDE dying.  So probably not helpful.

Platform details:
Windows 7 Pro 64 16GB RAM
Python 2.7 32 bit (whatever is the latest)
rtmidi2 installed via "pip install rtmidi2".  It shows the same version as on github: 0.5.4
I have tried both midi outs on my system with the same issue.  These outputs are:
CoolSoft VirtualMIDISynth and Microsoft GS Wavetable Synth

**Comment by gesellkammer** [comment]
The docstring is explicit that it expects a list of channels, midinotes and
velocities. You are providing an integer for channel.

**Comment by gesellkammer** [comment]
New checks added to prevent this, channel can be an int also.

**Comment by gesellkammer** [comment]
Also, the version in PyPI is not the latest. To use pip to install via
github use


pip install git+https://github.com/gesellkammer/rtmidi2@master#egg=rtmidi2

**Comment by Demolishun** [comment]
Thanks for getting on this so quickly.  I was just following the example on the "Send Multiple Notes at Once" section of the README.rst file.  It has almost verbatim what I was attempting.  I figured that "should" work.  Any, appreciate the fix.
Cheers.
