### ISSUE TITLE
All messages must be 3 bytes long?

### ISSUE THREAD

**Issue by tekhedd** [gesellkammer/rtmidi2#3]
Maybe I am missing something, but it appears from the source that only 3-byte-long messages are supported. This makes sending Program Change or messages impossible, or at least hackish. For example, send_message((0xc0, program)) results in a "parameter must be an int" error.) 

You can pad it out with an invalid byte (0x00) but of course this is invalid MIDI.

**Comment by Kopiller** [comment]
Yep and no support for sending sysex

**Comment by gesellkammer** [comment]
What do you need: program change or arbitrarily long midi messages?

**Comment by Kopiller** [comment]
I need to send sysex messages but arbitrary long raw messages will do the trick (like the c implementation) thanks

**Comment by gesellkammer** [comment]
Fixed in 0.7, now messages can be of arbitrary length, sysex implemented also
