### ISSUE TITLE
ValueError: ['PATH'] when trying to install

### ISSUE THREAD

**Issue by chmedly** [gesellkammer/rtmidi2#6]
I'm trying to install rtmidi2 on winxp Python3.4 but get this error.  If I try pip3 install rtmidi2 I also get the same error but also a note about the compile failing with code 1. Googling makes me think that there is something wrong with the way setuptools is used that sometimes causes this problem.

**Comment by gesellkammer** [comment]
Can you post the complete traceback?

**Comment by chmedly** [comment]
How's this?  

C:\Documents and Settings\Alphonso>pip3 install rtmidi2
Collecting rtmidi2
  Using cached rtmidi2-0.7.0.tar.gz
Installing collected packages: rtmidi2
  Running setup.py install for rtmidi2 ... error
    Complete output from command c:\python34\python.exe -u -c "import setuptools
, tokenize;__file__='C:\\DOCUME~1\\Alphonso\\LOCALS~1\\Temp\\pip-build-mfm07bxq\\r
tmidi2\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().repl
ace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --rec
ord C:\DOCUME~1\Alphponso\LOCALS~1\Temp\pip-9e13vqmf-record\install-record.txt --si
ngle-version-externally-managed --compile:
    version: 0.7.0
    running install
    running build
    running build_ext
    cythoning rtmidi2.pyx to rtmidi2.cpp
    building 'rtmidi2' extension
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\DOCUME~1\Alphonso\LOCALS~1\Temp\pip-build-mfm07bxq\rtmidi2\setup.py
", line 65, in <module>
        'Topic :: Software Development :: Libraries :: Python Modules'
      File "c:\python34\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "c:\python34\lib\distutils\dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "c:\python34\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "c:\python34\lib\site-packages\setuptools\command\install.py", line 6
1, in run
        return orig.install.run(self)
      File "c:\python34\lib\distutils\command\install.py", line 539, in run
        self.run_command('build')
      File "c:\python34\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\python34\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "c:\python34\lib\distutils\command\build.py", line 126, in run
        self.run_command(cmd_name)
      File "c:\python34\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\python34\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "c:\python34\lib\site-packages\Cython\Distutils\old_build_ext.py", li
ne 185, in run
        _build_ext.build_ext.run(self)
      File "c:\python34\lib\distutils\command\build_ext.py", line 339, in run
        self.build_extensions()
      File "c:\python34\lib\site-packages\Cython\Distutils\old_build_ext.py", li
ne 193, in build_extensions
        self.build_extension(ext)
      File "c:\python34\lib\distutils\command\build_ext.py", line 503, in build_
extension
        depends=ext.depends)
      File "c:\python34\lib\distutils\msvc9compiler.py", line 460, in compile
        self.initialize()
      File "c:\python34\lib\distutils\msvc9compiler.py", line 371, in initialize

        vc_env = query_vcvarsall(VERSION, plat_spec)
      File "c:\python34\lib\site-packages\setuptools\msvc9_support.py", line 52,
 in query_vcvarsall
        return unpatched['query_vcvarsall'](version, *args, **kwargs)
      File "c:\python34\lib\distutils\msvc9compiler.py", line 287, in query_vcva
rsall
        raise ValueError(str(list(result.keys())))
    ValueError: ['path']

    ----------------------------------------
Command "c:\python34\python.exe -u -c "import setuptools, tokenize;__file__='C:\
\DOCUME~1\\Alphonso\\LOCALS~1\\Temp\\pip-build-mfm07bxq\\rtmidi2\\setup.py';f=geta
ttr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.clos
e();exec(compile(code, __file__, 'exec'))" install --record C:\DOCUME~1\Alphonso\L
OCALS~1\Temp\pip-9e13vqmf-record\install-record.txt --single-version-externally-
managed --compile" failed with error code 1 in C:\DOCUME~1\Alphonso\LOCALS~1\Temp\
pip-build-mfm07bxq\rtmidi2\

**Comment by gesellkammer** [comment]
You don't seem to have a compiler installed. rtmidi2 is a python wrapper 
around a C++ library for crossplatform midi. You need a compiler to 
install it.

**Comment by chmedly** [comment]
hmm.  I followed the steps here for 'C++ 10.0.0 standalone'. https://wiki.python.org/moin/WindowsCompilers#Microsoft_Visual_C.2B-.2B-_10.0_standalone:_Windows_SDK_7.1_.28x86.2C_x64.2C_ia64.29

As far as I can tell, everything is installed.  Any clues what I'm missing?

**Comment by chmedly** [comment]
So, I took a look at things and decided to update setuptools.  After that I get this...
C:\Documents and Settings\Alphonso>pip install Cython
Requirement already satisfied: Cython in c:\python34\lib\site-packages

C:\Documents and Settings\Alphonso>pip3 install rtmidi2
Collecting rtmidi2
  Using cached rtmidi2-0.7.0.tar.gz
Installing collected packages: rtmidi2
  Running setup.py install for rtmidi2 ... error
    Complete output from command c:\python34\python.exe -u -c "import setuptools
, tokenize;__file__='C:\\DOCUME~1\\Alphonso\\LOCALS~1\\Temp\\pip-build-i4w9spzk\\r
tmidi2\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().repl
ace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --rec
ord C:\DOCUME~1\Alphonso\LOCALS~1\Temp\pip-9c7io227-record\install-record.txt --si
ngle-version-externally-managed --compile:
    version: 0.7.0
    running install
    running build
    running build_ext
    cythoning rtmidi2.pyx to rtmidi2.cpp
    building 'rtmidi2' extension
    creating build
    creating build\temp.win32-3.4
    creating build\temp.win32-3.4\Release
    creating build\temp.win32-3.4\Release\RtMidi
    c:\Program Files\Microsoft Visual Studio 10.0\VC\Bin\cl.exe /c /nologo /Ox /
MD /W3 /GS- /DNDEBUG -D__WINDOWS_MM__ -Ic:\python34\include -Ic:\python34\includ
e /Tprtmidi2.cpp /Fobuild\temp.win32-3.4\Release\rtmidi2.obj
    rtmidi2.cpp
    c:\Program Files\Microsoft Visual Studio 10.0\VC\Include\xlocale(323) : warn
ing C4530: C++ exception handler used, but unwind semantics are not enabled. Spe
cify /EHsc
    c:\Program Files\Microsoft Visual Studio 10.0\VC\Include\intrin.h(26) : fata
l error C1083: Cannot open include file: 'ammintrin.h': No such file or director
y
    error: command 'c:\\Program Files\\Microsoft Visual Studio 10.0\\VC\\Bin\\cl
.exe' failed with exit status 2

    ----------------------------------------
Command "c:\python34\python.exe -u -c "import setuptools, tokenize;__file__='C:\
\DOCUME~1\\Alphonso\\LOCALS~1\\Temp\\pip-build-i4w9spzk\\rtmidi2\\setup.py';f=geta
ttr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.clos
e();exec(compile(code, __file__, 'exec'))" install --record C:\DOCUME~1\Alphonso\L
OCALS~1\Temp\pip-9c7io227-record\install-record.txt --single-version-externally-
managed --compile" failed with error code 1 in C:\DOCUME~1\Alphonso\LOCALS~1\Temp\
pip-build-i4w9spzk\rtmidi2\

**Comment by gesellkammer** [comment]
These errors are not related to rtmidi2. You don't seem to really know 
what you are doing, mixing python 2 and python 3. Maybe this is not the 
software you are looking for.

**Comment by chmedly** [comment]
Technical comment: 
It looks like you are correct. This is a Microsoft problem and not an rtmidi2 problem.  https://connect.microsoft.com/VisualStudio/feedback/details/660584/windows-update-kb2455033-breaks-build-with-missing-ammintrin-h
The SP1 update to the compiler causes an issue with 'ammintrin.h'
And because this largely only affects WinXP, which is deprecated they don't intend to fix it.  

Personal comment:
You may also be right that I don't know what I'm doing but I DO have rtmidi2 installed and working correctly on Win10 as well as MacOS running the latest pieces (ie python 3.6).  I posted this 'issue' thinking that either:
A)  You (and others) would appreciate knowing that there was a compatibility issue with the installer; if there was one.       -or
B)  You would immediately know where my problem was and save me re-creating the wheel sorting out the installer issue.  

It appears that it's neither (or maybe a little of both?).  But I do think this is a likely issue that someone would encounter when trying to install rtmidi2 on python 3.4 on winXP.  My efforts down this path have been about testing my Python app on XP to see if it's a viable [option] platform for it.  I appreciate your work on rtmidi2 and hope I haven't wasted anyone's time.  And I hope this might be helpful for someone else at some point.
