### ISSUE TITLE
error creating OS-X MIDI client object.

### ISSUE THREAD

**Issue by chmedly** [gesellkammer/rtmidi2#7]
I had rtmidi2 working fine in a previous version of this app but I've rewritten it so that multiple midi devices can communicate with the software at once and I'm creating each instance of rtmidi2 in it's own Qthread class.  With this new code I have what appear to be random problems with this initialize error. The problem seems to be limited to MacOs platform only - Windows 10 seems fine.  
On Yosemite I get the following.  
```
MidiInCore::initialize: error creating OS-X MIDI client object.

libc++abi.dylib: terminating with uncaught exception of type RtMidiError: MidiInCore::initialize: error creating OS-X MIDI client object.
```
On Sierra I get an additional nugget:
```
MidiInCore::initialize: error creating OS-X MIDI client object (-50).

libc++abi.dylib: terminating with uncaught exception of type RtMidiError: MidiInCore::initialize: error creating OS-X MIDI client object (-50).
```
This error is happening during the instantiation of the rtmidi class but before the Qthread is actually started. 
 Any ideas?

**Comment by gesellkammer** [comment]
To listen to multiple ports at the same time use MidiInMulti
